version: '3.2'
services:
  localstack:
    image: localstack/localstack:0.11.1
    container_name: localstack
    ports:
      - '4566:4566'
      - '8055:8080'
    environment:
      # add more services seperated by commas: SERVICES=s3,sqs,dynamodb,dynamodbstreams
      # docs at: https://github.com/localstack/localstack#overview
      - SERVICES=lambda,dynamodb,sqs,s3,ses,iam
      - LAMBDA_EXECUTOR=docker-reuse
      - DEBUG=1
      - DEFAULT_REGION=eu-central-1
      - USE_SSL=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
